# Generated by Django 5.1.1 on 2024-09-19 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='cotent',
            new_name='content',
        ),
    ]
