# Generated by Django 5.1.1 on 2024-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0002_rename_cotent_reviewmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='useful_review',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
